# path
env_model_name: 'Table'
env_model_path: 'model/env/table/table.obj'

# environment
obj_model_name: 
  - 'up_glucose_bottle'
  - 'i_am_a_bunny_book'
  - 'expo_dry_erase_board_eraser'

obj_model_path: 
  - 'model/objects/up_glucose_bottle/up_glucose_bottle.obj'
  - 'model/objects/i_am_a_bunny_book/i_am_a_bunny_book.obj'
  - 'model/objects/expo_dry_erase_board_eraser/expo_dry_erase_board_eraser.obj'

camera:
  num_poses: 3
  camera_poses: [[-0.16, -1.6, 1.3, 0.8, 0.56, 0, 0], [1.1, 0.0, 1.3, 0.56, 0.4, 0.4, 0.56], [0, 0, 2.0, 0.7, 0.0, 0.0, 0.7]]
  camera_intrinsics: [[619.444214, 0.0, 320],[0.0, 619.444336, 240],[0.0, 0.0, 1.0]]

params:
  num_images: 10
  label_type: box
  minimum_objects_in_scene: 2
  maximum_objects_in_scene: 3
  range_x: [-0.40, 0.30]
  range_y: [-0.24, 0.24]
  range_z: [0.9, 1.2]
  num_simulation_steps: 80
  light_position_range_x: [0.8, 1.2]
  light_position_range_y: [-0.12, 0.12]
  light_position_range_z: [1.5, 2.0]

iter_num : 50